# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3']
        wabt-tag: ['1.0.35']
        wabt-asset: ['wabt-1.0.35-ubuntu-20.04.tar.gz']

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install wabt 1.0.35
      uses: robinraju/release-downloader@v1.10
      with:
        repository: 'WebAssembly/wabt'
        tag: ${{ matrix.wabt-tag }}
        fileName: ${{ matrix.wabt-asset }}
        extract: true
    - name: Add wabt binaries to PATH
      run: |
        WABTASSET=${{ matrix.wabt-asset }}
        WABTDIR="${WABTASSET%-ubuntu*}"
        echo "$GITHUB_WORKSPACE/$WABTDIR/bin/" >> $GITHUB_PATH
    - name: Test
      run: dotnet test --no-build --verbosity normal
