# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3']
        wabt-tag: ['1.0.35']
        wabt-asset: ['wabt-1.0.35-ubuntu-20.04.tar.gz']

    steps:
    - name: Install WebAssembly/wabt
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: WebAssembly/wabt
        platform: ubuntu
        arch: "-20" # workaround because wabt release files don't contain an architecture
        cache: enable
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install wabt 1.0.35
      uses: robinraju/release-downloader@v1.10
      with:
        repository: 'WebAssembly/wabt'
        tag: ${{ matrix.wabt-tag }}
        fileName: ${{ matrix.wabt-asset }}
        extract: true
    - name: Add wabt binaries to PATH
      run: |
        WABTASSET=${{ matrix.wabt-asset }}
        WABTDIR="${WABTASSET%-ubuntu*}"
        echo "$GITHUB_WORKSPACE/$WABTDIR/bin/" >> $GITHUB_PATH
    - name: Run tests
      run: bundle exec rake test
